apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.db.env.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.db.env.POSTGRES_DB }}
